[server]
runOnSave = true
headless = true
enableStaticServing = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "light"

[runner]
magicEnabled = true
fastReruns = true

[global]
developmentMode = false
